/* Generated by tex3ds */
#pragma once

#define sprites_msg_idx 0
#define sprites_arrow_back_idx 1
#define sprites_button_b_idx 2
#define sprites_button_blue_idx 3
#define sprites_button_red_idx 4
#define sprites_button_shadow_idx 5
#define sprites_button_msg_idx 6
#define sprites_button_msg_shadow_idx 7
#define sprites_cursor_idx 8
#define sprites_icon_female_idx 9
#define sprites_icon_male_idx 10
#define sprites_icon_msg_idx 11
#define sprites_icon_question_idx 12
#define sprites_item_button_idx 13
#define sprites_photo_bg_idx 14
#define sprites_logo_horiHD_idx 15
#define sprites_logo_rocketrobz_idx 16
#define sprites_title_idx 17
#define sprites_titleMetal_idx 18
#define sprites_logo_UniversalCore_idx 19
#define sprites_homeicon_idx 20
